# üèÉ‚Äç‚ôÄÔ∏è Continuous Integration and Delivery: Branch Testing
# ======================================================


---

name: üîÅ Branch integration testing


# Driving Event
# -------------
#
# What event starts this workflow: a push to any branch other than main

on:
    push:
        branches:
            -   '**'
            -   '!main'
    workflow_dispatch:


# What to Do
# ----------
#
# Test the software with mvn test

jobs:
    branch-testing:
        name: ü™µ Branch Testing
        runs-on: ubuntu-latest
        if: github.actor != 'pdsen-ci'

        strategy:
            matrix:
                java-version: [17]

        steps:
            -
                name: üí≥ Checkout
                uses: actions/checkout@v4
                with:
                    lfs: true
                    fetch-depth: 0
                    token: ${{secrets.ADMIN_GITHUB_TOKEN || github.token}}
                    path: registry-harvest-legacy
            -
                name: üíµ Maven Cache
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    # The "key" used to indicate a set of cached files is the operating system runner
                    # plus "mvn" for Maven-specific builds, plus a hash of the `pom.xml` files, which
                    # should uniquely identify the dependent jars; plus "pds" because we pds-prefix
                    # everything with "pds" in PDS‚Äîeven when the context is obvious! üòÖ
                    key: pds-${{runner.os}}-mvn-${{hashFiles('**/pom.xml')}}
                    # To restore a set of files, we only need to match a prefix of the saved key.
                    restore-keys: pds-${{runner.os}}-mvn-
            -
                name: ‚òïÔ∏è Set up OpenJDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'adopt'
                    java-version: ${{matrix.java-version}}
            -
                name: ü©∫ Test, Build, and Unpack Harvest Software
                run: |
                    pwd
                    cd registry-harvest-legacy
                    mvn test package
                    cd $GITHUB_WORKSPACE
                    tar -xvzf registry-harvest-legacy/target/harvest-legacy-*-bin.tar.gz

            -
                name: üí≥ Checkout Registry Manager Repo
                uses: actions/checkout@v4
                with:
                    repository: NASA-PDS/registry-mgr-legacy
                    lfs: true
                    fetch-depth: 0
                    token: ${{secrets.ADMIN_GITHUB_TOKEN || github.token}}
                    path: registry-mgr-legacy

            -
                name: Build Registry Manager
                run: |
                    pwd
                    cd registry-mgr-legacy
                    mvn clean package
                    cd $GITHUB_WORKSPACE
                    tar -xvzf registry-mgr-legacy/target/registry-mgr-legacy-*-bin.tar.gz

            -
                name: ü©∫ Run Smoke Tests
                run: |
                    echo "Prep environment"
                    cd cd $GITHUB_WORKSPACE
                    mkdir registry-data
                    export DATA_HOME=$GITHUB_WORKSPACE/registry-data
                    export LEGACY_REGISTRY_HOME=$GITHUB_WORKSPACE/registry-mgr-legacy-*/
                    export LEGACY_HARVEST_HOME=$GITHUB_WORKSPACE/harvest-legacy-*/
                    cd registry-harvest-legacy/test
                    ./smoke-tests.sh

...

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
